# usage: conda env create -p $(pwd)/miniconda/envs/power_calc_genetics --file environment.yaml 
# -p flag should point to your miniconda installation path.

# name of the conda environment
name: power_calc_genetics

# the paths that conda takes a look for packages. 
# avoid using anaconda as we have experienced issues with it
channels:
        - conda-forge
        - bioconda
        - defaults

#install following packages in the conda environment
dependencies:
        - r-optparse
        - r-pwr
        - r-here
        - r-dt
